name: Auto Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Random Commits
        run: |
          git config --local user.name "name"
          git config --local user.email "email"

          count=$((RANDOM % 11))

          if [ $count -eq 0 ]; then
            exit 0
          fi

          for i in $(seq 1 $count); do
            echo "$(date "+%Y-%m-%d %H:%M:%S")-$count" > log.txt
            git add log.txt
            git commit -m "$(date "+%Y-%m-%d %H:%M:%S")-$count-[skip ci]"
          done

          git push origin main
